{
 "title": "Web Performance PageSpeed Insight Metrics",
 "description": "PageSpeed Insight for Lapakgaming and Joytfiy (Mobile and Desktop scores)",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Lapakgaming PDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.lapakgaming.com/id-id/mobile-legends\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Performance Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.lapakgaming.com/id-id/mobile-legends\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "psi_first_contentful_paint{site=\"https://www.lapakgaming.com/id-id/mobile-legends\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "psi_largest_contentful_paint{site=\"https://www.lapakgaming.com/id-id/mobile-legends\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "psi_cumulative_layout_shift{site=\"https://www.lapakgaming.com/id-id/mobile-legends\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Total Blocking Time (TBT) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "psi_total_blocking_time{site=\"https://www.lapakgaming.com/id-id/mobile-legends\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Lapakgaming Home Page", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Performance Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.lapakgaming.com/id-id\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Performance Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.lapakgaming.com/id-id\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "psi_first_contentful_paint{site=\"https://www.lapakgaming.com/id-id\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "psi_largest_contentful_paint{site=\"https://www.lapakgaming.com/id-id\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "psi_cumulative_layout_shift{site=\"https://www.lapakgaming.com/id-id\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Total Blocking Time (TBT) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "psi_total_blocking_time{site=\"https://www.lapakgaming.com/id-id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "LG Home Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.lapakgaming.com/id-id\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "LG PDP Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.lapakgaming.com/id-id/mobile-legends\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Joytify Home Page Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.joytify.com/en-us\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Joytify PDP Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.joytify.com/en-us/mobile-legends\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Performance Score All Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    { "expr": "psi_performance_score{}" }
   ]
  },
  { "title": "Joytify Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Performance Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.joytify.com/en-us\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Performance Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.joytify.com/en-us\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "psi_first_contentful_paint{site=\"https://www.joytify.com/en-us\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "psi_largest_contentful_paint{site=\"https://www.joytify.com/en-us\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 66 },
   "targets": [
    {
     "expr": "psi_cumulative_layout_shift{site=\"https://www.joytify.com/en-us\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Total Blocking Time (TBT) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "psi_total_blocking_time{site=\"https://www.joytify.com/en-us\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Joytify PDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Performance Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.joytify.com/en-us/mobile-legends\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Performance Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "psi_performance_score{site=\"https://www.joytify.com/en-us/mobile-legends\"} * 100",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "psi_first_contentful_paint{site=\"https://www.joytify.com/en-us/mobile-legends\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 85 },
   "targets": [
    {
     "expr": "psi_largest_contentful_paint{site=\"https://www.joytify.com/en-us/mobile-legends\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 85 },
   "targets": [
    {
     "expr": "psi_cumulative_layout_shift{site=\"https://www.joytify.com/en-us/mobile-legends\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Total Blocking Time (TBT) ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "psi_total_blocking_time{site=\"https://www.joytify.com/en-us/mobile-legends\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}